services:
  postgresql:
    container_name: weather_api_db
    image: postgres:latest
    environment:
      POSTGRES_DB: weather_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d weather_api" ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - weather_api_app

  app:
    container_name: weather-api
    image: openjdk:21-jdk-alpine
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/weather_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./target/weather-api-0.0.1-SNAPSHOT.jar:/app.jar
    command: [ "java", "-jar", "/app.jar" ]
    restart: always
    networks:
      - weather_api_app
    depends_on:
      postgresql:
        condition: service_healthy

networks:
  weather_api_app: