server:
  port: 8080

openweathermap:
  limit: ${LIMIT}
  api-key: ${OPENWEATHERMAP_API_KEY}
  expired-time: PT10M

app:
  name: The weather API
  description: An application to retrieve weather report by city name
  version: v.1.0.0
  email: weather-api@gmail.com

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql_17_db:5432/weather_api_db
    username: postgres
    password: ${POSTGRES_PASSWORD:123}

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      format_sql: true
      highlight_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
      com.kameleoon.weatherapi.client.ExternalWeatherApi: DEBUG

  sql:
    init:
      mode: always

  application:
    name: The weather API SDK
