CREATE TABLE IF NOT EXISTS weather_report
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_date TIMESTAMP(6) WITH TIME ZONE,
    visibility  INTEGER,
    date_time   BIGINT,
    time_zone   INTEGER,
    name        VARCHAR(255),
    main        VARCHAR(255),
    description VARCHAR(255),
    temp        DOUBLE PRECISION,
    feels_like  DOUBLE PRECISION,
    speed       DOUBLE PRECISION,
    sunrise     BIGINT,
    sunset      BIGINT
);

CREATE TABLE IF NOT EXISTS city_info
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255),
    latitude          DOUBLE PRECISION,
    longitude         DOUBLE PRECISION,
    country           VARCHAR(255),
    state             VARCHAR(255),
    weather_report_id INTEGER,
    CONSTRAINT fk_city_info_weather_report
        FOREIGN KEY (weather_report_id) REFERENCES weather_report (id) ON DELETE CASCADE
);
