--CREATE TABLE city_info
--(
--    id        SERIAL PRIMARY KEY,
--    name      VARCHAR(255)     NOT NULL,
--    latitude  DOUBLE PRECISION NOT NULL,
--    longitude DOUBLE PRECISION NOT NULL,
--    country   VARCHAR(255),
--    state     VARCHAR(255)
--);
--
--CREATE TABLE weather_report
--(
--    id                  SERIAL PRIMARY KEY,
--    create_date         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
--    change_date         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
--    city_id             INT              NOT NULL,
--    weather_main        VARCHAR(255),
--    weather_description VARCHAR(255),
--    temp                DOUBLE PRECISION NOT NULL,
--    feels_like          DOUBLE PRECISION NOT NULL,
--    visibility          INT,
--    wind_speed          DOUBLE PRECISION NOT NULL,
--    date_time           BIGINT           NOT NULL,
--    sys_sunrise         BIGINT,
--    sys_sunset          BIGINT,
--    time_zone           INT,
--    name                VARCHAR(255),
--    FOREIGN KEY (city_id) REFERENCES city_info (id) ON DELETE CASCADE
--);
--
--CREATE INDEX idx_weather_report_city_id ON weather_report (city_id);

create table if not exist city_info (
         id integer generated by default as identity primary key,
         country varchar(255),
         latitude double precision,
         longitude double precision,
         name varchar(255),
         state varchar(255)
     );

create table if not exist weather_report (
         id integer generated by default as identity primary key,
         change_date timestamp(6) with time zone,
         create_date timestamp(6) with time zone,
         date_time bigint,
         name varchar(255),
         sunrise bigint,
         sunset bigint,
         feels_like double precision,
         temp double precision,
         time_zone integer,
         visibility integer,
         description varchar(255),
         main varchar(255),
         speed double precision,
         city_id integer not null,
         foreign key (city_id) references city_info(id) on delete cascade);
     );
--
--2025-03-19 12:46:49 2025-03-19T08:46:49.525Z DEBUG 1 --- [           main] org.hibernate.SQL                        :
--2025-03-19 12:46:49     set client_min_messages = WARNING
--2025-03-19 12:46:49 Hibernate:
--2025-03-19 12:46:49     set client_min_messages = WARNING
--2025-03-19 12:46:49 2025-03-19T08:46:49.528Z DEBUG 1 --- [           main] org.hibernate.SQL                        :
--2025-03-19 12:46:49     alter table if exists weather_report
--2025-03-19 12:46:49        drop constraint if exists FK616la7vla8r9n6y6jprggdjxl
--2025-03-19 12:46:49 Hibernate:
--2025-03-19 12:46:49     alter table if exists weather_report
--2025-03-19 12:46:49        drop constraint if exists FK616la7vla8r9n6y6jprggdjxl
--2025-03-19 12:46:49 2025-03-19T08:46:49.530Z DEBUG 1 --- [           main] org.hibernate.SQL                        :
--2025-03-19 12:46:49     drop table if exists city_info cascade
--2025-03-19 12:46:49 Hibernate:
--2025-03-19 12:46:49     drop table if exists city_info cascade
--2025-03-19 12:46:49 2025-03-19T08:46:49.532Z DEBUG 1 --- [           main] org.hibernate.SQL                        :
--2025-03-19 12:46:49     drop table if exists weather_report cascade
--2025-03-19 12:46:49 Hibernate:
--2025-03-19 12:46:49     drop table if exists weather_report cascade
--2025-03-19 12:46:49 2025-03-19T08:46:49.539Z DEBUG 1 --- [           main] org.hibernate.SQL                        :
--2025-03-19 12:46:49     create table city_info (
--2025-03-19 12:46:49         id integer generated by default as identity,
--2025-03-19 12:46:49         latitude float(53),
--2025-03-19 12:46:49         longitude float(53),
--2025-03-19 12:46:49         country varchar(255),
--2025-03-19 12:46:49         name varchar(255),
--2025-03-19 12:46:49         state varchar(255),
--2025-03-19 12:46:49         primary key (id)
--2025-03-19 12:46:49     )
--2025-03-19 12:46:49 Hibernate:
--2025-03-19 12:46:49     create table city_info (
--2025-03-19 12:46:49         id integer generated by default as identity,
--2025-03-19 12:46:49         latitude float(53),
--2025-03-19 12:46:49         longitude float(53),
--2025-03-19 12:46:49         country varchar(255),
--2025-03-19 12:46:49         name varchar(255),
--2025-03-19 12:46:49         state varchar(255),
--2025-03-19 12:46:49         primary key (id)
--2025-03-19 12:46:49     )
--2025-03-19 12:46:49 2025-03-19T08:46:49.548Z DEBUG 1 --- [           main] org.hibernate.SQL                        :
--2025-03-19 12:46:49     create table weather_report (
--2025-03-19 12:46:49         city_id integer not null,
--2025-03-19 12:46:49         feels_like float(53),
--2025-03-19 12:46:49         id integer generated by default as identity,
--2025-03-19 12:46:49         speed float(53),
--2025-03-19 12:46:49         temp float(53),
--2025-03-19 12:46:49         time_zone integer,
--2025-03-19 12:46:49         visibility integer,
--2025-03-19 12:46:49         change_date timestamp(6) with time zone,
--2025-03-19 12:46:49         create_date timestamp(6) with time zone,
--2025-03-19 12:46:49         date_time bigint,
--2025-03-19 12:46:49         sunrise bigint,
--2025-03-19 12:46:49         sunset bigint,
--2025-03-19 12:46:49         description varchar(255),
--2025-03-19 12:46:49         main varchar(255),
--2025-03-19 12:46:49         name varchar(255),
--2025-03-19 12:46:49         primary key (id)
--2025-03-19 12:46:49     )
--2025-03-19 12:46:49 Hibernate:
--2025-03-19 12:46:49     create table weather_report (
--2025-03-19 12:46:49         city_id integer not null,
--2025-03-19 12:46:49         feels_like float(53),
--2025-03-19 12:46:49         id integer generated by default as identity,
--2025-03-19 12:46:49         speed float(53),
--2025-03-19 12:46:49         temp float(53),
--2025-03-19 12:46:49         time_zone integer,
--2025-03-19 12:46:49         visibility integer,
--2025-03-19 12:46:49         change_date timestamp(6) with time zone,
--2025-03-19 12:46:49         create_date timestamp(6) with time zone,
--2025-03-19 12:46:49         date_time bigint,
--2025-03-19 12:46:49         sunrise bigint,
--2025-03-19 12:46:49         sunset bigint,
--2025-03-19 12:46:49         description varchar(255),
--2025-03-19 12:46:49         main varchar(255),
--2025-03-19 12:46:49         name varchar(255),
--2025-03-19 12:46:49         primary key (id)
--2025-03-19 12:46:49     )
--2025-03-19 12:46:49 2025-03-19T08:46:49.553Z DEBUG 1 --- [           main] org.hibernate.SQL                        :
--2025-03-19 12:46:49     alter table if exists weather_report
--2025-03-19 12:46:49        add constraint FK616la7vla8r9n6y6jprggdjxl
--2025-03-19 12:46:49        foreign key (city_id)
--2025-03-19 12:46:49        references city_info
--2025-03-19 12:46:49 Hibernate:
--2025-03-19 12:46:49     alter table if exists weather_report
--2025-03-19 12:46:49        add constraint FK616la7vla8r9n6y6jprggdjxl
--2025-03-19 12:46:49        foreign key (city_id)
--2025-03-19 12:46:49        references city_info